name: Maven CI/CD

on:
  push:
    branches: [master]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11

      - name: Download war artifact
        uses: actions/download-artifact@v4
        with:
          name: docs-web-ci.war
          path: docs-web/target

      - name: Setup up Docker Buildx
        uses: docker/setup-buildx-action@v1
        if: github.event_name != 'pull_request'

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Populate Docker metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: hfan045/teedy-app
          flavor: |
            latest=false
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable=${{ github.ref_type != 'tag' }}
          labels: |
            org.opencontainers.image.created = ${{ github.event_created_at }}
            org.opencontainers.image.author = Sismics
            org.opencontainers.image.url = https://teedy.io/
            org.opencontainers.image.version = ${{ github.event_head_commit.id }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
